-- Run this in Supabase SQL Editor.
-- Existing public.products remains the approved/live product catalogue.
create table if not exists public.product_submissions (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 100),
  price bigint not null check (price >= 0),
  category text not null default 'Other' check (char_length(category) <= 50),
  image_url text,
  description text not null default '' check (char_length(description) <= 500),
  created_at timestamptz not null default now()
);

alter table public.product_submissions enable row level security;

-- Visitors may submit only. Public visitors cannot read, update, or delete submissions.
grant insert on table public.product_submissions to anon, authenticated;
grant usage, select on sequence public.product_submissions_id_seq to anon, authenticated;
revoke select, update, delete on table public.product_submissions from anon, authenticated;

drop policy if exists "Anyone can submit products for review" on public.product_submissions;
create policy "Anyone can submit products for review"
on public.product_submissions
for insert
to anon, authenticated
with check (
  char_length(name) between 1 and 100
  and price >= 0
  and char_length(category) <= 50
  and char_length(description) <= 500
);

-- Ensure the public can view the approved catalogue only.
alter table public.products enable row level security;
drop policy if exists "Anyone can read available products" on public.products;
create policy "Anyone can read available products"
on public.products for select to anon, authenticated using (true);

-- Keep product changes restricted to authenticated users. Further restrict this to
-- explicitly designated admins before creating admin accounts in the future.
